### PR TITLE
bump Azure.Identity to 1.10.2

### PR DESCRIPTION
**Pull request by oleksandr-didyk**
Resolves internal [CG alert](https://dev.azure.com/dnceng/internal/_componentGovernance/dotnet-dnceng-shared/alert/8729354?typeId=15101106&pipelinesTrackingFilter=0)

### CODE REVIEW

**Review by dkurepa — APPROVED** [review]

**Comment by premun** [comment]
@oleksandr-didyk why not go for the newest? `1.10.3`?

**Comment by oleksandr-didyk** [comment]
> @oleksandr-didyk why not go for the newest? `1.10.3`?

Since we are not automatically updating to newest I updated to the version that would satisfy the alert (i.e. I don't know if there is a reason for us not being on latest patch). 

If we can consume latest minor / patch, maybe it should be part of automatic updates?

**Comment by dkurepa** [comment]
In general, we always try to go for the newest, especially if it's just a version bump

**Comment by premun** [comment]
> If we can consume latest minor / patch, maybe it should be part of automatic updates?

What do you mean? We do not have any automatic updates for these libraries.

> I don't know if there is a reason for us not being on latest patch

We should be because we're really just causing more alerts on the road by going step by step

**Comment by oleksandr-didyk** [comment]
> What do you mean? We do not have any automatic updates for these libraries.

I would just expect there to be some automation for bumping these libraries (like a Dependabot or something similar) if we can consume latest. Otherwise we are just reactively bumping the versions whenever CG complains.

Or are these updates so rare that having automatic updates is not justified?

**Comment by premun** [comment]
There's no automatic updates because we are first mirroring packages to the AzDO feed and do not consume them from nuget.org automatically for security reasons.

**Pull request merged**
