### PR TITLE
Add editorconfig and the open source header to all files

### PR DESCRIPTION
**Pull request by dkurepa**
https://github.com/dotnet/arcade/issues/13243

### CODE REVIEW

**Review by premun — COMMENTED** [review]
Can you check some new files from say runtime? I have also seen a 2-line LICENSE and I don't know which one is the most up-to-date

**Comment by dkurepa** [comment]
most repos are using a 2 line license currently, it's the same as the one we are using, it just doesn't have the `See the LICENSE file in the project root for more information.` line

**Comment by premun** [comment]
Ah, right, I never read the text 😅

**Review by premun — DISMISSED** [review]

**Comment by dkurepa** [comment]
do you think we should drop that line too?

**Comment by premun** [comment]
I am only afraid that when we'd be moving files in/out of this repo, it would start flagging these and that's what I'd prevent but I have no preference in which header is better. What the rest is using we should be using. I believe it might be the 2-line one

**Comment by dkurepa** [comment]
Yup, that makes sense, I changed it to the 2 line one

**Comment by premun** [comment]
@dkurepa can we revisit whether we need to build both Debug and Release in the PR build?

**Comment by dkurepa** [comment]
That part was copied from arcade-services, where we have the service fabric projects. We probably don't need to build those in debug in this repo? I'll start the conversation in the V-Team chat. That's a good point

**Pull request merged**
